# Originally copied from: https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/fluentd-gcp
# Also see the post: http://blog.kubernetes.io/2015/06/cluster-level-logging-with-kubernetes.html

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logrotate
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: logrotate
    spec:
      dnsPolicy: Default
      containers:
      - name: logrotate
        image: mumoshu/kube-logrotate:0.1.0
        resources:
          limits:
            memory: 10Mi
          requests:
        # Any change here should be accompanied by a proportional change in CPU
        # requests of other per-node add-ons (e.g. kube-proxy).
            cpu: 10m
            memory: 10Mi
        env:
        - name: LOGROTATE_ARGS
          value: -v
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name: mntsda1
          mountPath: /mnt/sda1
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: mntsda1
        hostPath:
          path: /mnt/sda1
